spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/embark_ecom

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  app:
    jwtSecret: thuyPhuocThinh_learn_spring_boot
    jwtExpirationMs: 3000000000
    jwtCookieName: jwt

project:
  images: images/
  baseUrl: http://localhost:8080/

logging:
  level:
    org:
      springframework: DEBUG
      hibernate:
        SQL: DEBUG
    com:
      tpt: DEBUG
