spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/embark_ecom

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true